[build]
  functions = "netlify/functions"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless", "bcrypt", "jsonwebtoken"]
  included_files = ["netlify/functions/**"]

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - serve index.html for all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
