[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - serve index.html for all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
